초기화 후 설치 실패 해결
amd

Signed-off-by: flavono123 <flavono123@gmail.com>

diff --git a/bash/.bash_profile.d/k8s b/bash/.bash_profile.d/k8s
--- a/bash/.bash_profile.d/k8s
+++ b/bash/.bash_profile.d/k8s
@@ -1,13 +1,17 @@
 # vim: ft=sh
 
-# Bash completion v2
-[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"
-
-# k8s alias and auto complete
-source <(kubectl completion bash)
-alias k=kubectl
-complete -F __start_kubectl k
-export do="--dry-run=client -o yaml"
-
-# watch
-alias watch='watch '
+if ! command -v kubectl; then
+  echo "${BASH_SOURCE}: 'kubectl' could not be found"
+else
+  # Bash completion v2
+  [[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"
+  
+  # k8s alias and auto complete
+  source <(kubectl completion bash)
+  alias k=kubectl
+  complete -F __start_kubectl k
+  export do="--dry-run=client -o yaml"
+  
+  # watch
+  alias watch='watch '
+fi
diff --git a/bash/.bash_profile.d/pyenv b/bash/.bash_profile.d/pyenv
--- a/bash/.bash_profile.d/pyenv
+++ b/bash/.bash_profile.d/pyenv
@@ -1,3 +1,7 @@
 # vim: ft=sh
 
-eval "$(pyenv init --path)"
+if ! command -v pyenv; then
+  echo "${BASH_SOURCE}: 'pyenv' could not be found"
+else
+  eval "$(pyenv init --path)"
+fi
diff --git a/bash/.bash_profile.d/rbenv b/bash/.bash_profile.d/rbenv
--- a/bash/.bash_profile.d/rbenv
+++ b/bash/.bash_profile.d/rbenv
@@ -1,5 +1,9 @@
 # vim: ft=sh
 
-export PATH="$HOME/.rbenv/bin:$PATH"
+if ! command -v rbenv; then
+  echo "${BASH_SOURCE}: 'rbenv' could not be found"
+else
+  export PATH="$HOME/.rbenv/bin:$PATH"
 
-eval "$(rbenv init -)"
+  eval "$(rbenv init -)"
+fi
