bash: Suppress when bash_profile run
- remove gcp concern, not using now
- suppress `command' command's output
- suppress when `command` failed
  - pyenv

- why? for show!

Signed-off-by: flavono123 <flavono123@gmail.com>

diff --git a/bash/.bash_profile.d/pyenv b/bash/.bash_profile.d/pyenv
--- a/bash/.bash_profile.d/pyenv
+++ b/bash/.bash_profile.d/pyenv
@@ -1,7 +1,7 @@
 # vim: ft=sh
 
-if ! command -v pyenv; then
-  echo "${BASH_SOURCE}: 'pyenv' could not be found"
+if ! command -v pyenv > /dev/null; then
+  : # echo "${BASH_SOURCE}: 'pyenv' could not be found"
 else
   eval "$(pyenv init --path)"
 fi
